server:
  port: 8083
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  data:
    mongodb:
      database: Clients
      host: localhost
      port: 27017

